mode="optimize"

[optimize]
method ="hybrid"
search_radius = 0.05
converge = 0.01
max_iterations = 15

[parameters]
main={nominal=8.48071629e-01} 
secondary={nominal=5.68694462e-01}
third={nominal=1.29890115}


Ibiasz={nominal=4.89847382e-05}
L1={nominal=9.26791487e-12}
L2={nominal=9.27100210e-12} 
Lout={nominal=1.54646489e-12}
retentionResistor={nominal=4}



[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "oAND.sp"
circuit = "oAND.js"
threshold = 0.2