mode="margin"

[parameters]

b1  	=	 {nominal =     1.30033373e+00}
b3  	=	 {nominal =     1.74400646e+00}
b4  	=	 {nominal =     6.79982243e-01}
b7  	=	 {nominal =     5.26031505e-01}
b8  	=	 {nominal =     1.32265353e+00}
b9  	=	 {nominal =     8.16000559e-01}
i1  	=	 {nominal =     2.32768744e-04}
l1  	=	 {nominal =     4.22915406e-12}
l3  	=	 {nominal =     2.49358577e-12}
l4  	=	 {nominal =     1.18894186e-11}
l5  	=	 {nominal =     1.74432575e-10}
l6  	=	 {nominal =     1.29835538e-12}
r1   	=	 {nominal =     5.33437400e-01}



[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "AW_OR.sp"
circuit = "AW_OR_testbench_optimized.cir"
threshold = 0.1