mode="optimize"

[optimize]
method ="hybrid"
search_radius = 0.05
converge = 0.01
max_iterations = 10

[parameters]
B1 ={nominal=2.5, min=2.5}
B2 ={nominal=1.79}
B3 ={nominal=2.5}
B4 ={nominal=2.5}
B5 ={nominal=1.79, max=2.5}
B6 ={nominal=2.5}
B7 ={nominal=2.5}

IB1 ={nominal=175E-6}
IB2 ={nominal=250E-6}
IB3 ={nominal=175E-6}
IB4 ={nominal=175E-6}

L1 ={nominal=2.067834e-12}
L2 ={nominal=4.135667E-12}
L3 ={nominal=8.271335E-12}
L4 ={nominal=4.135667E-12}
L5 ={nominal=2.067834e-12}
L6 ={nominal=4.135667E-12}
L7 ={nominal=2.067834e-12}

[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "DFF.sp"
circuit = "tb_DFF_base.js"
threshold = 0.35