mode="margin"

[parameters]
B_JIA={nominal=    1.08172342e+00}
B_JUA={nominal=    9.98731934e-01}
B_JLA={nominal=    9.61678975e-01}

B_JIB={nominal=    9.77749297e-01}
B_JUB={nominal=    1.09557322e+00}
B_JLB={nominal=    1.16185870e+00 }

B_JP ={nominal=    5.19248148e-01}
B_JPS ={nominal=    4.07603769e-01}
B_JLIM={nominal=    1.96555868e+00 }


Ibias={nominal=    2.53670849e-04 }

LBias={nominal=    3.46560565e-10}
Lpoff={nominal=    1.29760632e-11}
Rs   ={nominal=    9.90210690e-01 }
RH   ={nominal=    2.95746005e+00 }

LP  ={nominal=     8.19946788e-13}
RP  ={nominal=     1.08687967e+00}




[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "OR.sp"
circuit = "OR.js"
threshold = 0.1