mode="optimize"

[optimize]
method ="hybrid"
search_radius = 0.05
converge = 0.01
max_iterations = 15

[parameters]
Bps={nominal=4.750e-01}
Bp={nominal=6.650e-01}
Bia={nominal=1.140}
Bib={nominal=1.140}
Bua={nominal= 1.050}
Bub={nominal=1.050}
Bla={nominal=1.365}
Blb={nominal=1.235}
Blim={nominal=1.890}

LBias ={nominal=3.325e-10}
Lpoff ={nominal= 1.520e-11}
Rs={nominal=9.500e-01}
RH={nominal= 3.800}
IB1={nominal= 1.050e-04}



[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "OR.sp"
circuit = "OR.js"
threshold = 0.2