mode="margin"

[parameters]



b1  =    {nominal =    5.16417451e-01}
b3  =    {nominal =    3.12658647e-01}
b5  =    {nominal =    1.05188201e+00}
i1  =    {nominal =    3.26322383e-05}
l1  =    {nominal =    3.51004037e-12}
l3  =    {nominal =    1.17410569e-12}
r1  =    {nominal =    8.40028656e-01}
r3  =    {nominal =    1.76782953e+00}




[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "AND.sp"
circuit = "AW_AND_testbench_optimized.cir"
threshold = 0.1