mode="optimize"

[optimize]
method ="hybrid"
search_radius = 0.05
converge = 0.01
max_iterations = 15

[parameters]

Ibias={nominal=70e-6}
main={nominal=0.84}
secondary={nominal=0.60}
third={nominal=1.68}

retentionResistor={nominal=6.1405}
RL ={nominal= 0.667}
Lout={nominal=2e-12}


[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "AND.sp"
circuit = "AND.js"
threshold = 0.15