mode="optimize"

[optimize]
method ="hybrid"
search_radius = 0.05
converge = 0.01
max_iterations = 15

[parameters]
Bps={nominal=0.5}
Bp={nominal=0.7}
Bia={nominal=1.2}
Bib={nominal=1.2}
Bua={nominal=1}
Bub={nominal=1}
Bla={nominal=1.3}
Blb={nominal=1.3}
Blim={nominal=1.8}

LBias ={nominal=350E-12}
Lpoff ={nominal=16E-12}
Rs={nominal=1}
RH={nominal=4}
IB1={nominal=270E-6}



[margin]
binary_search_steps = 7

[verify]
method = "spec_file"
file = "OR.sp"
circuit = "OR.js"
threshold = 0.2